cloudforet-io/console-api-v2

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/CI_branch_tagging.yml
- .github/workflows/CI_create_release_branch.yml
- .github/workflows/CI_make_helm_chart.yaml
- .github/workflows/CI_master_push.yml
- .github/workflows/CI_reflect_branch_update_to_master.yml
- Dockerfile
- deploy/helm/Chart.yaml
- deploy/helm/config/config.yaml
- deploy/helm/config/nginx.conf
- deploy/helm/config/proxy.conf
- deploy/helm/templates/NOTES.txt
- deploy/helm/templates/_helpers.tpl
- deploy/helm/templates/application-grpc-conf.yaml
- deploy/helm/templates/application-rest-conf.yaml
- deploy/helm/templates/application-scheduler-conf.yaml
- deploy/helm/templates/application-worker-conf.yaml
- deploy/helm/templates/database-conf.yaml
- deploy/helm/templates/default-conf.yaml
- deploy/helm/templates/deployment-grpc.yaml
- deploy/helm/templates/deployment-rest.yaml
- deploy/helm/templates/deployment-scheduler.yaml
- deploy/helm/templates/deployment-worker.yaml
- deploy/helm/templates/ingress-rest.yaml
- deploy/helm/templates/rest-nginx-conf.yaml
- deploy/helm/templates/rest-nginx-proxy-conf.yaml
- deploy/helm/templates/service-grpc.yaml
- deploy/helm/templates/service-rest.yaml
- deploy/helm/templates/shared-conf.yaml
- deploy/helm/values.yaml
> Add files for build 

- deploy/helm/Chart.yaml
> Fix Chart.yaml version

- pkg/pip_requirements.txt
- src/cloudforet/console_api/model/dashboard/domain_dashboard.py
- src/cloudforet/console_api/model/dashboard/project_dashboard.py
- src/cloudforet/setup.py
- update changed model spec for domain_dashboard and project_dashboard
- add setup.py
* #2
> Update changed model spec for domain_dashboard and project_dashboard

- src/cloudforet/console_api/interface/rest/dashboard/domain_dashboard.py
- src/cloudforet/console_api/interface/rest/dashboard/project_dashboard.py
- src/cloudforet/console_api/service/common/proxy_service.py
- Fix dispatch_api method in proxy_service.py
- dispatch_api method doesn't pass `params`
* #2
> Fix dispatch_api method in proxy_service.py

- src/cloudforet/console_api_v2/conf/global_conf.py
- src/cloudforet/console_api_v2/model/dashboard/domain_dashboard.py
- src/cloudforet/console_api_v2/model/dashboard/project_dashboard.py
- modify and remove log config 
- remove user_id field at Create class
-API spec Changed so i applied it.
* #2
> Remove user_id field at Create class

- src/cloudforet/console_api_v2/conf/router_conf.py
- src/cloudforet/console_api_v2/interface/rest/inventory/change_history.py
- src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service.py
- src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service_tag.py
- src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service_type.py
- src/cloudforet/console_api_v2/interface/rest/inventory/collector.py
- src/cloudforet/console_api_v2/interface/rest/inventory/job.py
- src/cloudforet/console_api_v2/interface/rest/inventory/job_task.py
- src/cloudforet/console_api_v2/interface/rest/inventory/note.py
- src/cloudforet/console_api_v2/interface/rest/inventory/region.py
- src/cloudforet/console_api_v2/interface/rest/inventory/resource_group.py
- add Inventory apis
- only pass-through apis
* #17
> Add Inventory apis

- src/cloudforet/console_api_v2/conf/router_conf.py
> Fix router_conf.py

- src/cloudforet/console_api_v2/conf/router_conf.py
- src/cloudforet/console_api_v2/interface/rest/notification/notification.py
- src/cloudforet/console_api_v2/interface/rest/notification/notification_usage.py
- src/cloudforet/console_api_v2/interface/rest/notification/project_channel.py
- src/cloudforet/console_api_v2/interface/rest/notification/protocol.py
- src/cloudforet/console_api_v2/interface/rest/notification/quota.py
- src/cloudforet/console_api_v2/interface/rest/notification/user_channel.py
> add notification apis

- src/cloudforet/console_api_v2/interface/rest/cost_analysis/budget_usage.py
- src/cloudforet/console_api_v2/interface/rest/cost_analysis/cost.py
- modify grpc method name in interface
> Modify grpc method name in interface

- src/cloudforet/console_api_v2/model/inventory/cloud_service.py
- Modify ip_address name and type in Inventory.cloud_service
- list -> str 
- ip_addresses -> ip_address
* #17
> Modify ip_address name and type in Inventory.cloud_service

- src/cloudforet/console_api_v2/interface/rest/identity/domain.py
- src/cloudforet/console_api_v2/interface/rest/identity/token.py
- remove auth from identity.Token apis
- executed NoAuth
- remove auth from identity.Domain.list api
- executed NoAuth
* #20
> Remove auth from identity apis

- src/cloudforet/console_api_v2/interface/rest/identity/domain.py
- src/cloudforet/console_api_v2/interface/rest/identity/project.py
- src/cloudforet/console_api_v2/interface/rest/identity/token.py
- src/cloudforet/console_api_v2/interface/rest/identity/user.py
- src/cloudforet/console_api_v2/model/identity/project.py
- src/cloudforet/console_api_v2/model/identity/user.py
- update identity apis document
* #20
> Update identity apis document

- src/cloudforet/console_api_v2/model/dashboard/domain_dashboard.py
- modify labels field type dict -> list
> Modify labels field type dict -> list

- src/cloudforet/console_api_v2/interface/rest/cost_analysis/cost.py
- src/cloudforet/console_api_v2/model/cost_analysis/cost.py
- modify cost apis description
> Modify cost apis description

- src/cloudforet/console_api_v2/conf/global_conf.py
- src/cloudforet/console_api_v2/interface/rest/identity/project.py
- src/cloudforet/console_api_v2/interface/rest/identity/token.py
- src/cloudforet/console_api_v2/interface/rest/identity/user.py
- src/cloudforet/console_api_v2/model/identity/token.py
- modify identity apis description
> Modify identity apis description

- src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service.py
- src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service_type.py
- src/cloudforet/console_api_v2/interface/rest/inventory/region.py
- modify inventory apis description
> Modify inventory apis description

- src/cloudforet/console_api_v2/conf/router_conf.py
> Remove deprecated router

- src/cloudforet/console_api_v2/interface/rest/identity/domain.py
- remove identity.Domain.list api
> Remove identity.Domain.list api

- src/cloudforet/console_api_v2/interface/rest/identity/user.py
- src/cloudforet/console_api_v2/model/identity/user.py
- src/cloudforet/console_api_v2/model/inventory/region.py
> Add apis for notification email and reset password

- src/cloudforet/console_api_v2/interface/rest/identity/user.py
- src/cloudforet/console_api_v2/model/identity/user.py
- add VerifyEmailRequest mode
- ass reset_password api 
* #44
> Add api and Model for identity.User

- src/cloudforet/console_api_v2/model/identity/token.py
-  add verify_code field at IssueTokenRequest api
> Add verify_code field at IssueTokenRequest api

- src/cloudforet/console_api_v2/interface/rest/identity/user.py
- modify reset_password api without auth
* #44
> Modify reset_password api without auth (#44)

- src/cloudforet/console_api_v2/interface/rest/identity/user.py
- src/cloudforet/console_api_v2/model/identity/user.py
- add reset_password filed at UserUpdateRequest
- remove return value of delete method at identity.User
* #31
> Add reset_password filed at UserUpdateRequest

- deploy/helm/config/nginx.conf
- src/cloudforet/console_api_v2/conf/router_conf.py
- src/cloudforet/console_api_v2/error/__init__.py
- src/cloudforet/console_api_v2/error/resource.py
- src/cloudforet/console_api_v2/interface/rest/extension/resource.py
- src/cloudforet/console_api_v2/manager/resource_manager/__init__.py
- src/cloudforet/console_api_v2/manager/resource_manager/cost_analysis_manager.py
- src/cloudforet/console_api_v2/manager/resource_manager/inventory_manager.py
- src/cloudforet/console_api_v2/model/extension/resource.py
- src/cloudforet/console_api_v2/service/extension/resource_service.py
- add resource APIs for autocomplete
- change nginx.conf
> Add APIs and Change NGINX Configuration

- deploy/helm/Chart.yaml
> build: update helm chart version

- src/cloudforet/console_api_v2/model/identity/token.py
- src/cloudforet/console_api_v2/model/identity/user.py
- modify api spec for identity.User
- add force field at VerifyEmailRequest 
* #44
> Modify api spec for identity.User

- src/cloudforet/console_api_v2/conf/router_conf.py
- src/cloudforet/console_api_v2/interface/rest/plugin/plugin.py
feat: Add API - plugin service (get-metadata)
> Add API get-metadata for plugin service

- src/cloudforet/console_api_v2/interface/rest/inventory/job.py
- add analyze API for `inventory.Job`
> feat: add analyze API of inventory.Job

- src/cloudforet/console_api_v2/interface/rest/plugin/plugin.py
> Modify get-plugin-metadata

- src/cloudforet/console_api_v2/interface/rest/api.py
- src/cloudforet/console_api_v2/interface/rest/proxy.py
- fix console-api-v2 reflection bug
* #57
> Fix console-api-v2 reflection bug

- src/cloudforet/console_api_v2/conf/global_conf.py
> Modify swagger title

- src/cloudforet/console_api_v2/conf/router_conf.py
- add api reflection api for backwards compatibility
* #57
> Add reflection api for backwards compatibility

- Dockerfile
- pkg/pip_requirements.txt
- src/setup.py
- modify docker base image to python-core:2.0
* #57
> Modify docker base image to python-core:2.0

- Dockerfile
- add Dockerfile build args 'BRANCH_NAME'
> Add Dockerfile build args 'BRANCH_NAME'

- src/cloudforet/console_api_v2/interface/rest/api.py
- src/cloudforet/console_api_v2/interface/rest/proxy.py
- src/cloudforet/console_api_v2/interface/rest/swagger.py
- modify cacheable parameter name 'backend' -> 'alias'
> Modify cacheable parameter name 'backend' -> 'alias'

- deploy/helm/Chart.yaml
- deploy/helm/templates/deployment-scheduler.yaml
- deploy/helm/templates/deployment-worker.yaml
> Update chart version

- deploy/helm/config/proxy.conf
- add timeout values at nginx conf
> Add timeout values at nginx conf

- src/cloudforet/console_api_v2/interface/rest/proxy.py
- Modify convert 'resource' logic for APIKey at proxy.py
> Modify convert 'resource' logic for APIKey at proxy.py

- src/cloudforet/console_api_v2/conf/global_conf.py
- src/cloudforet/console_api_v2/conf/router_conf.py
- src/cloudforet/console_api_v2/interface/rest/auth.py
- src/cloudforet/console_api_v2/manager/cloudforet_manager.py
- src/cloudforet/console_api_v2/model/auth/request.py
- src/cloudforet/console_api_v2/service/auth_service.py
- add Auth.basic_auth api for token validation
> Add Auth.basic_auth api for token validation

- src/cloudforet/console_api_v2/conf/global_conf.py
- src/cloudforet/console_api_v2/interface/rest/auth.py
- src/cloudforet/console_api_v2/manager/cloudforet_manager.py
- src/cloudforet/console_api_v2/model/auth/request.py
- src/cloudforet/console_api_v2/service/auth_service.py
- modify Auth request field name
> Modify Auth request field name

- src/cloudforet/console_api_v2/interface/rest/auth.py
- modify http_authorization location query parameter to header
> Modify http_authorization location query parameter to header

- src/cloudforet/console_api_v2/interface/rest/auth.py
- src/cloudforet/console_api_v2/service/auth_service.py
> Modify auth model

- src/cloudforet/console_api_v2/conf/global_conf.py
- src/cloudforet/console_api_v2/service/auth_service.py
* Add masking to conceal token log in global_conf
> feat: add masking to conceal token log in global_conf

- src/cloudforet/console_api_v2/conf/global_conf.py
- src/cloudforet/console_api_v2/service/auth_service.py
- src/cloudforet/console_api_v2/service/proxy_service.py
> Add log filter rules

- src/cloudforet/console_api_v2/conf/global_conf.py
- modify openapi_json_dirs for identity v2
> Modify openapi_json_dirs for identity v2

- deploy/helm/Chart.yaml
- deploy/helm/config/config.yaml
> build: change helm chart

- src/cloudforet/console_api_v2/conf/global_conf.py
> Add Search service at global_conf.py

- src/cloudforet/console_api_v2/conf/global_conf.py
- fix typo at OPEN_JSON_DIRS at global_conf.py
> Fix typo at OPEN_JSON_DIRS at global_conf.py

- src/cloudforet/console_api_v2/service/auth_service.py
> Fix get public key error

- src/cloudforet/console_api_v2/service/agent_service.py
- src/cloudforet/console_api_v2/service/auth_service.py
I have added a logic for authentication when installing the agent in the user's cluster in service account agent mode.
> Add service account agent mode basich auth

- src/cloudforet/console_api_v2/manager/cloudforet_manager.py
- src/cloudforet/console_api_v2/service/auth_service.py
I added a `_check_app` logic to check the `last_accessed_at` of `app_info`.
> Add app check for state

- src/cloudforet/console_api_v2/conf/router_conf.py
- src/cloudforet/console_api_v2/interface/rest/extension/agent.py
- src/cloudforet/console_api_v2/interface/rest/extension/auth.py
- src/cloudforet/console_api_v2/service/agent_service.py
The `router_path` of `auth` has been modified to be under `extension`, and the existing data is now fetched from Agent Info instead of Service Account Info.
> Modify code that data comes from agent info

- src/cloudforet/console_api_v2/conf/global_conf.py
- src/cloudforet/console_api_v2/service/agent_service.py
- [] Refactor
Add global configs about OpenCost
> Add global configs about opencost

- src/cloudforet/console_api_v2/service/agent_service.py
Check agent's option using any, not all
> Check agent's option using any, not all

- src/cloudforet/console_api_v2/service/agent_service.py
Change boolean variable because of response
> Change boolean variable because of response

- src/cloudforet/console_api_v2/service/agent_service.py
Change boolean values to convert to yaml
> Change boolean values to convert to yaml

- src/cloudforet/console_api_v2/service/agent_service.py
> Change opencost yaml format

- pkg/pip_requirements.txt
- src/setup.py
- add require package (`typing-inspect`)
> build: add require package

- src/cloudforet/console_api_v2/interface/rest/extension/auth.py
- src/cloudforet/console_api_v2/service/auth_service.py
This feature not only provides the Metadata XML for the Service Provider but also allows for more efficient API calls through code optimization.
> Add SAML feature and optimize the code

- src/cloudforet/console_api_v2/service/auth_service.py
> Delete https option

- src/cloudforet/console_api_v2/service/auth_service.py
> Change https option

- src/cloudforet/console_api_v2/service/auth_service.py
Add unauthorized case if credentials don't exist
> Add unauthorized case if credentials don't exist

- src/cloudforet/console_api_v2/service/auth_service.py
Redirect to the error page if refresh_token doesn't exist
> Redirect to error page if refresh_token doesn't exist

- pkg/pip_requirements.txt
Add python-multipart as Fast API upgraded
> Add python-multipart as Fast API upgraded

- src/cloudforet/console_api_v2/conf/global_conf.py
- add new service path at global_conf for 'opsflow'
> Add new service path at global_conf for 'opsflow'

- src/cloudforet/console_api_v2/conf/global_conf.py
- Add description at global_conf for 'inventory-v2'
> Add description at global_conf for 'inventory-v2'

- src/cloudforet/console_api_v2/conf/global_conf.py
> add: add alert manager conf

- src/cloudforet/console_api_v2/conf/global_conf.py
- src/cloudforet/console_api_v2/handler/authentication_handler.py
- src/cloudforet/console_api_v2/interface/rest/proxy.py
- src/cloudforet/console_api_v2/service/agent_service.py
- src/cloudforet/console_api_v2/service/auth_service.py
- src/cloudforet/console_api_v2/service/proxy_service.py
- modify global_conf.py authentication handler
> Modify global_conf.py authentication handler

- Dockerfile
- src/cloudforet/console_api_v2/handler/authentication_handler.py
- modify Dockerfile add default value for BRANCH_NAME
> Modify Dockerfile add default value for BRANCH_NAME

- src/cloudforet/console_api_v2/handler/authentication_handler.py
> refactor: change jwt utils

- src/cloudforet/console_api_v2/handler/authentication_handler.py
> fix: fix type bug

- pkg/pip_requirements.txt
- src/cloudforet/console_api_v2/service/auth_service.py
- Add Jinja2 template for SAML loading
> Add Jinja2 template for SAML loading

- src/cloudforet/console_api_v2/conf/global_conf.py
> feat: update masking rules
